export const pokemons = [
  {
    name: "Pikachu",
    types: ["Electric"],
    abilities: [
      { name: "Static", hidden: false },
      { name: "Lightning Rod", hidden: true },
    ],
    stats: {
      hp: 35,
      attack: 55,
      defense: 40,
      specialAttack: 50,
      specialDefense: 50,
      speed: 90,
    },
    height: 4,
    weight: 60,
    baseExperience: 112,
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
    isLegendary: false,
  },
  {
    name: "Bulbasaur",
    types: ["Grass", "Poison"],
    abilities: [
      { name: "Overgrow", hidden: false },
      { name: "Chlorophyll", hidden: true },
    ],
    stats: {
      hp: 45,
      attack: 49,
      defense: 49,
      specialAttack: 65,
      specialDefense: 65,
      speed: 45,
    },
    height: 7,
    weight: 69,
    baseExperience: 64,
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
    isLegendary: false,
  },
  {
    name: "Charizard",
    types: ["Fire", "Flying"],
    abilities: [
      { name: "Blaze", hidden: false },
      { name: "Solar Power", hidden: true },
    ],
    stats: {
      hp: 78,
      attack: 84,
      defense: 78,
      specialAttack: 109,
      specialDefense: 85,
      speed: 100,
    },
    height: 17,
    weight: 905,
    baseExperience: 240,
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
    isLegendary: false,
  },
  {
    name: "Mewtwo",
    types: ["Psychic"],
    abilities: [
      { name: "Pressure", hidden: false },
      { name: "Unnerve", hidden: true },
    ],
    stats: {
      hp: 106,
      attack: 110,
      defense: 90,
      specialAttack: 154,
      specialDefense: 90,
      speed: 130,
    },
    height: 20,
    weight: 1220,
    baseExperience: 340,
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png",
    isLegendary: true,
  },
  {
    name: "Gengar",
    types: ["Ghost", "Poison"],
    abilities: [
      { name: "Cursed Body", hidden: true },
    ],
    stats: {
      hp: 60,
      attack: 65,
      defense: 60,
      specialAttack: 130,
      specialDefense: 75,
      speed: 110,
    },
    height: 15,
    weight: 405,
    baseExperience: 225,
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png",
    isLegendary: false,
  },
];